language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libiomp-dev libboost-dev libgtest-dev libopenmpi-dev libsparsehash-dev
script:
  - ./autogen.sh
  - ./configure --with-mpi=/usr/lib/openmpi
  - make
  - make check
